version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    #Entry point
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=development
      #environment variable to load the app config for the development environment
      - APP_SETTINGS-src.config.DevelopmentConfig
      #Add teh database portion
      - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/api_dev  
      - DATABASE_TEST_URL=postgresql://postgres:postgres@api-db:5432/api_test  
    depends_on:  
      - api-db

  api-db: 
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres